# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('description', models.TextField(verbose_name='Description')),
                ('duration', models.PositiveSmallIntegerField(verbose_name='Duration')),
                ('avatar', models.ImageField(upload_to='', verbose_name='avatar')),
            ],
            options={
                'verbose_name_plural': 'projects',
                'verbose_name': 'project',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('description', models.TextField(verbose_name='Description')),
                ('start', models.DateTimeField(auto_now_add=True, verbose_name='Start')),
                ('end', models.DateTimeField(verbose_name='End')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'incomplete'), (1, 'complete')], verbose_name='Status')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Project', verbose_name='Project')),
            ],
            options={
                'verbose_name_plural': 'tasks',
                'verbose_name': 'task',
            },
        ),
    ]
